# **Introduction to Python**

## **01 - The Python Basic**


**Python Interface**

In [1]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


**Python as calculator**

In [2]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# Calculate two to the power of five
print(2**5)

10
0
15
5.0
4
16
32


**Calculations with varibles**

In [3]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = (savings * growth_multiplier ** 7)

# Print out result
print(result)

194.87171000000012


**Operations with other types**

In [4]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of savings and growth_multiplier to year1
year1 = (savings * growth_multiplier)

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
print(doubledesc)

<class 'float'>
compound interestcompound interest


**Type Conversion**

In [5]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

I started with $100 and now have $194.87171000000012. Awesome!


In [6]:
print(True + False)
print(True - False)
print(True * False)
print(True ** True)
print(True ** False)
print(False ** True)
# print(False / False)  #ZeroDivisionError: division by zero
# print(True / False)  #ZeroDivisionError: division by zero
print(True / True)

1
1
0
1
1
0
1.0


In [7]:
print("a" * 4)
print("a" + str(4))
print(str(3) + str(4))

aaaa
a4
34


## **02 - Python List**

**Create a list**

In [8]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


**Creating the list with differnet types**

In [9]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


**List of List**

In [10]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


**Subset and conquer**

In [11]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])


11.25
9.5
20.0


In [12]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


**Slicing and dicing**

In [13]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(len(areas))
print(downstairs)
print(upstairs)

10
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [14]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[6:]

print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [15]:
house = [['hallway', 11.25],
         ['kitchen', 18.0],
         ['living room', 20.0],
         ['bedroom', 10.75],
         ['bathroom', 9.5]]

# What will house[-1][1] return?
# Ans: float: the bathroom area

house[-1][1]

9.5

**Replace list Elements**

In [16]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# finding the location of the particular element in the list
print(areas.index(9.50))
print(areas[areas.index(9.50)])

# Correct the bathroom area
areas[9] = 10.50
print(areas[9]) 

# Change "living room" to "chill zone"
print(areas.index("living room"))
areas[4] = "chill zone"
print(areas[4])

9
9.5
10.5
4
chill zone


**Extend a list**

In [17]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

print(areas)
print(areas_1)
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


**Delete list elements**

In [18]:
# del function 
areas = ["hallway", 11.25, "kitchen", 18.0,
         "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

print(len(areas))
del(areas[10]); del(areas[11])
print(len(areas))
print(areas)

14
12
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 24.5, 15.45]


In [19]:
# del function 
areas = ["hallway", 11.25, "kitchen", 18.0,
         "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

print(len(areas))
del(areas[-4:-2])
print(len(areas))
print(areas)

14
12
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [20]:
new_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(new_list[0])
print(new_list[1])
print(new_list[-1])
print(new_list[-4])
print(new_list[-2])
print("-----------")
print(new_list[-4:])
print(new_list[:-2])
print(new_list[-4:-2])
print("-----------")
print(new_list[::2])
print(new_list[::-1])
print(new_list[::-2])

1
2
10
7
9
-----------
[7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8]
[7, 8]
-----------
[1, 3, 5, 7, 9]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 8, 6, 4, 2]


**Inner Working of lists**

In [21]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## **03 - Functions and Packages**

In [22]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


In [23]:
help(pow)
?pow

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



**Multiple arguments**

In [24]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


**String Method**

In [25]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

poolhouse
POOLHOUSE
3


**List Methods**

In [26]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


In [27]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)



[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


**Import Package**

In [28]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*(r**2)

# Build printout
# print("Circumference: " + str(C))
# print("Area: " + str(A))
print("Circumference: ", C)
print("Area: ", A)

Circumference:  2.701769682087222
Area:  0.5808804816487527


**Selective Import**

In [29]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
phi = radians(12)
dist = r * phi

# Print out dist
print(dist)

40317.10572106901


**Different ways of importing**

In [30]:
from scipy.linalg import inv 
inv([[1,2], 
    [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## **04 - NumPy**

In [31]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


**height conversion: inch → meter**

In [32]:
# height_in is available as a regular list
height_in = [74, 74, 72, 72, 73, 69, 69, 70]

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 72 73 69 69 70]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.778 ]


**Body mass index Calculator**

In [33]:
# height_in and weight_lb are available as regular lists
height_in = [74, 74, 72, 72, 73, 69, 69, 70, 80, 81]
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180]

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m)**2

# Create the lightb weight array
light_weight = np.array(bmi < 21)

# Print out lightb weight
print(light_weight)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light_weight])

[False False False False False False False False False  True]
[19.28858727]


In [34]:
# Adding the two np arrarys
print(np.array([4, 3, 0]) + np.array([0, 2, 2]))

[4 5 2]


In [35]:
np.array([True, 1, 2, 3, 4, False])

array([1, 1, 2, 3, 4, 0])

In [36]:
print(np.array([1, 1, 2]) + np.array([3, 4, -1]))

[4 5 1]


In [37]:
print(np.array([True, True]) + np.array([True, 0]) )

[2 1]


In [38]:
print(np.array([True, True]) + np.array([True, False]))

[ True  True]


**Subsetting NumPy Arrays**

In [39]:
# height_in and weight_lb are available as a regular lists
height_in = [74, 74, 72, 72, 73, 69, 69, 70, 80, 81]
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180]

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[5])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[3:7])


176
[72 73 69 69]


**2D NumPy Array**

In [40]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2],
            [178, 65.2],
            [198, 85.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(np_baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)
print(np_baseball.ndim)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]
 [178.   65.2]
 [198.   85.2]]
(6, 2)
2


In [41]:
# Create baseball, a list of lists [height, weight]
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2],
            [178, 65.2],
            [198, 85.2]]

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# selecting the rows and column in the numpy array
column_heights = np_baseball[:, 0] # selecting the entire column
column_weights = np_baseball[:, 1] # selecting the entire column
row = np_baseball[1, :]            # Selecting the entire row
print(column_weights)
print(column_heights)
print(row)

# Print out the 4th row of np_baseball
print(np_baseball[4, :])

# Print out height of 2th player
print(np_baseball[2, 0])

[ 78.4 102.7  98.5  75.2  65.2  85.2]
[180. 215. 210. 188. 178. 198.]
[215.  102.7]
[178.   65.2]
210.0


**Numpy Statistics**

In [42]:
import numpy as np
x = [1, 4, 8, 10, 12]

print(np.mean(x))
print(np.median(x))

7.0
8.0


In [43]:
import numpy as np

# Create baseball, a list of lists [height, weight]
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2],
            [177, 64.4],
            [178, 65.6],
            [198, 85.2]]

np_baseball = np.array(baseball)
height = np_baseball[:, 0] # selecting the height column

print(type(np_baseball))
print(np.mean(height))
print(np.median(height))

weight = np_baseball[:, 1] # selecting the height column

print(type(np_baseball))
print(np.mean(weight))
print(np.median(weight))

<class 'numpy.ndarray'>
192.28571428571428
188.0
<class 'numpy.ndarray'>
81.42857142857144
78.4


**Exploring the data**

In [44]:
# Import numpy
import numpy as np

# Create baseball, a list of lists [height, weight]
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2],
            [177, 64.4],
            [178, 65.6],
            [198, 85.2]]

# Converting it into the numpy array
np_baseball = np.array(baseball)

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

Average: 192.28571428571428
Median: 188.0
Standard Deviation: 14.48855987829497
Correlation: [[1.         0.96499643]
 [0.96499643 1.        ]]


In [45]:
# Import numpy
import numpy as np

# list 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense)
positions = ['GK', 'M', 'A', 'D', 'GK', 'M', 'GK', 'D', 'A', 'D']
heights = [190, 184, 185, 180, 192, 184, 191, 180, 183, 184]

print(len(positions), len(heights))

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']
print("goal keepers height: ", list(gk_heights))

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']
print("Others height: ", list(other_heights))

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

10 10
goal keepers height:  [190, 192, 191]
Others height:  [184, 185, 180, 184, 180, 183, 184]
Median height of goalkeepers: 191.0
Median height of other players: 184.0
